# Generated by Django 6.0.5 on 2026-06-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('application', 'type')},
        ),
    ]
