# Generated by Django 6.0.5 on 2026-05-23 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('s1', 'S1 / Undergraduate'), ('s2', 'S2 / Master'), ('s3', 'S3 / Doctoral')], max_length=10)),
                ('requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
