# Generated by Django 6.0.5 on 2026-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='scholarship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='level',
            field=models.CharField(choices=[('s1', 'S1 / Undergraduate'), ('s2', 'S2 / Master'), ('s3', 'S3 / Doctoral')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='provider',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
